name: "BWA MQTT Bridge"
description: "BWA MQTT Bridge"
version: "1.0.0"
slug: "bwa_mqtt_bridge"
init: false
startup: application
services:
  - 'mqtt:need'
options:
  bridge_ip: '10.10.10.214'
  bridge_port: '9999'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
