name: "BWA MQTT Bridge"
description: "BWA MQTT Bridge"
version: "1.0.2"
slug: "bwa_mqtt_bridge"
init: false
startup: application
services:
  - 'mqtt:need'
options:
  bridge_ip: null
  bridge_port: null
schema: 
  bridge_ip: str
  bridge_port: port
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
